# Generated by Django 3.2.20 on 2023-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenuserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teenuserprofile',
            name='medical_id',
            field=models.IntegerField(blank=True, help_text='This is used for safeguarding compliance only', null=True, unique=True),
        ),
    ]
