# Generated by Django 3.2.20 on 2023-08-19 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20230818_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenuserprofile',
            name='medical_id',
            field=models.CharField(help_text='This is used for safeguarding compliance only', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='teenuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
