# Generated by Django 3.2.20 on 2023-08-19 14:53

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230819_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenuserprofile',
            name='date_of_birth',
            field=models.DateField(help_text='Format: 1900/12/31', null=True),
        ),
        migrations.AlterField(
            model_name='teenuserprofile',
            name='medical_id',
            field=models.CharField(help_text='Required: this is a 7 digit number found on your wristband', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(7)]),
        ),
    ]
