# Generated by Django 3.2.20 on 2023-08-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230819_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenuserprofile',
            name='fname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='first name'),
        ),
    ]
