# Generated by Django 3.2.20 on 2023-08-19 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('show_feedback', models.TextField(max_length=500)),
                ('feedback_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_updated', models.DateTimeField(auto_now_add=True)),
                ('feedback_approval', models.CharField(choices=[('PD', 'Pending'), ('OK', 'Okay')], default='PD', max_length=2)),
                ('room', models.CharField(choices=[('CHI', 'Crumlin'), ('SJH', 'St James'), ('CUH', 'Cork'), ('GUH', 'Galway')], default='CHI', help_text='Choose the room your feedback is for', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-show_feedback'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-show_feedback'], name='FEEDBACK_fe_show_fe_c0260a_idx'),
        ),
    ]
