# Generated by Django 3.2.20 on 2023-08-19 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FEEDBACK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_made',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
