# Generated by Django 3.2.20 on 2023-08-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FEEDBACK', '0002_auto_20230819_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('reply_made', models.DateTimeField(auto_now_add=True)),
                ('reply_updated', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['reply_made'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-published']},
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='FEEDBACK_fe_show_fe_c0260a_idx',
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-published'], name='FEEDBACK_fe_publish_3e5f96_idx'),
        ),
        migrations.AddField(
            model_name='feedbackreply',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reply', to='FEEDBACK.feedback'),
        ),
        migrations.AddIndex(
            model_name='feedbackreply',
            index=models.Index(fields=['reply_made'], name='FEEDBACK_fe_reply_m_28e188_idx'),
        ),
    ]
