# Generated by Django 3.2.20 on 2023-08-26 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FEEDBACK', '0003_auto_20230820_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='FeedbackPost',
        ),
        migrations.RemoveIndex(
            model_name='feedbackpost',
            name='FEEDBACK_fe_publish_3e5f96_idx',
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='feedbackpost',
            index=models.Index(fields=['-published'], name='FEEDBACK_fe_publish_28c453_idx'),
        ),
    ]
