# Generated by Django 3.2.20 on 2023-08-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEEDBACK', '0004_auto_20230826_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackpost',
            name='show_feedback',
            field=models.TextField(default='empty', max_length=500),
        ),
    ]
