# Generated by Django 3.2.20 on 2023-08-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEEDBACK', '0005_alter_feedbackpost_show_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackpost',
            name='feedback_approval',
            field=models.CharField(choices=[('PD', 'Pending'), ('OK', 'Okay')], default='OK', max_length=2),
        ),
        migrations.AlterField(
            model_name='feedbackreply',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
