# Generated by Django 3.2.20 on 2023-08-27 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('show_feedback', models.TextField(default='empty', max_length=500)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_made', models.DateTimeField(auto_now_add=True)),
                ('feedback_updated', models.DateTimeField(auto_now=True)),
                ('feedback_approval', models.CharField(choices=[('PD', 'Pending'), ('OK', 'Okay')], default='OK', max_length=2)),
                ('room', models.CharField(choices=[('CHI', 'Crumlin'), ('SJH', 'St James'), ('CUH', 'Cork'), ('GUH', 'Galway')], default='CHI', help_text='Choose the room your feedback is for', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('reply_made', models.DateTimeField(auto_now_add=True)),
                ('reply_updated', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(default=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reply', to='blog.feedbackpost')),
            ],
            options={
                'ordering': ['reply_made'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbackreply',
            index=models.Index(fields=['reply_made'], name='blog_feedba_reply_m_8121c2_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackpost',
            index=models.Index(fields=['-published'], name='blog_feedba_publish_824d15_idx'),
        ),
    ]
