# Generated by Django 3.2.20 on 2023-08-31 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('comment_made', models.DateTimeField(auto_now_add=True)),
                ('comment_updated', models.DateTimeField(auto_now=True, null=True)),
                ('allowed', models.BooleanField(default=True)),
                ('feedback_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_post', to='blog.feedbackpost')),
            ],
            options={
                'ordering': ['comment_made'],
            },
        ),
        migrations.DeleteModel(
            name='FeedbackReply',
        ),
        migrations.AddIndex(
            model_name='feedbackcomment',
            index=models.Index(fields=['comment_made'], name='blog_feedba_comment_fb4384_idx'),
        ),
    ]
