# Generated by Django 3.2.20 on 2023-08-31 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230831_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcomment',
            name='feedback_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.feedbackpost'),
        ),
    ]
