# Generated by Django 3.2.20 on 2023-09-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_feedbackcomment_feedback_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackpost',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
